# docker-compose.yml
version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - database
    ports:
      - "80:80"
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data: